### ISSUE TITLE
`ctx` referenced in example/meson.build but file's missing.

### ISSUE THREAD

**Issue by bartoszek** [hodefoting/mmm#2]
The 58892979d9725a0eda0e3aea373cdefd0b01f6a1 reference the example called `ctx` but there's no corresponding file available in the `/example`.
https://github.com/hodefoting/mmm/blob/58892979d9725a0eda0e3aea373cdefd0b01f6a1/examples/meson.build#L11

**Comment by hodefoting** [comment]
This got added my mistake, fixed in master.

It doesn't - at least not yet - make sense to add all of ctx as a static copy inside mmm for an example.
